1. throw表达式
程序的异常检测部分使用throw表达式引发一个异常。throw表达式包含关键字throw和紧随其后的一个表达式，其中表达式的类型就是抛出的异常类型。throw表达式后面通常紧跟一个分号，从而构成一条表达式语句。
``` C++
// 首先检查两条数据是否关于同一种书籍的
if (item1.isbn() != item2.isbn())
    throw runtime_error("Data must refer to same ISBN");
// 如果程序执行到了这里，表示两个ISBN是相同的
cout << item1 + item2 << endl;
```
2. try语句块
``` C++
try {
    program-statements
} catch (exception-declaration) {
    handler-statements
} catch (exception-declaration) {
    handler-statements
} // ···
```
* 跟在try块之后的是一个或者多个catch子句。catch子句包括三部分：关键字catch、括号内一个(可能未命名的)对象的声明（称作异常声明，exception declaration）以及一个块。当选中了某个catch子句处理异常之后，执行与之对应的块。catch一旦完成，程序跳转到try语句块最后一个catch子句之后的那条语句继续执行。
``` C++
while(cin >> item >> item2) {
    try {
        // 执行添加两个Sales_item对象的代码
        //如果添加失败，代码抛出一个runtime_error异常
        // 首先检查两条数据是否关于同一种书籍的
        if (item1.isbn() != item2.isbn())
            throw runtime_error("Data must refer to same ISBN");
        // 如果程序执行到了这里，表示两个ISBN是相同的
    } catch (runtime_error err) {
        // 提醒用户两个ISBN必须一致，询问是否重新输入
        cout << err.what()
             << "\nTry Again? Enter y or n" << endl;
        char c;
        cin >> c;
        if (!cin || c == 'n')   break;  // 跳出while循环
    }
}
```
* 当异常被抛出后，首先搜索抛出该异常的函数。如果没找到匹配的catch子句，终止该函数，并在调用函数的函数中继续寻找。如果还是没有找到匹配的catch子句，这个新的函数也被终止，继续搜索调用她的函数。依此类推，沿着程序的执行路径逐层回退，知道找到适当类型的catch子句为止。如果最终还是没能找到任何匹配的catch子句，程序转到名为terminate的标准库函数。该函数的行为与系统有关，一般情况下，执行该函数将导致 程序非正常退出。
3. stdexcept定义的异常类
[stdexcept定义的异常类](a.png)

